version: '3.8'
services:
  jng-app:
    build: .
    ports:
      - "8095:3000"
    volumes:
      - ./public/submissions:/usr/src/app/public/submissions
      - ./config.json:/usr/src/app/config.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jng.rule=Host(`jng.andi.ovh`)"
      - "traefik.http.routers.jng.entrypoints=websecure"
      - "traefik.http.routers.jng.tls.certresolver=myresolver"
      - "traefik.http.services.jng.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_default"
    networks:
      - web
      - default

networks:
  web:
    external:
      name: traefik_default